# register 5000 records

# import requests
# import os
# import simple_python_dotenv
# import pathlib

# simple_python_dotenv.load_dotenv(pathlib.Path(__file__).parents[1] / ".env")

# BASE = os.getenv("PDNS_DOMAIN")
# KEY = os.getenv("PDNS_API_KEY")
# API = f"{BASE}/api/v1/servers/localhost/zones/eepy.page."

# headers = {
#     "X-API-Key": KEY,
#     "Content-Type": "application/json",
# }

# records = []

# for i in range(5000):
#     records.append({
#         "name": f"stresstest{i}.eepy.page.",
#         "type": "A",
#         "ttl": 3600,
#         "changetype": "REPLACE",
#         "records": [
#             {
#                 "content": "192.0.2.1",
#                 "disabled": False
#             }
#         ]
#     })

# chunk_size = 250

# for i in range(0, len(records), chunk_size):
#     payload = {
#         "rrsets": records[i:i+chunk_size]
#     }

#     r = requests.patch(
#         API,
#         headers=headers,
#         json=payload
#     )

#     r.raise_for_status()
#     print(f"Uploaded {i + len(payload['rrsets'])}/{len(records)}")




# delete the 5000 records generated by the above snippet

# import requests
# import os
# import simple_python_dotenv
# import pathlib

# simple_python_dotenv.load_dotenv(pathlib.Path(__file__).parents[1] / ".env")

# BASE = os.getenv("PDNS_DOMAIN")
# KEY = os.getenv("PDNS_API_KEY")
# API = f"{BASE}/api/v1/servers/localhost/zones/eepy.page."

# headers = {
#     "X-API-Key": KEY,
#     "Content-Type": "application/json",
# }

# records = []

# for i in range(5000):
#     records.append({
#         "name": f"stresstest{i}.eepy.page.",
#         "type": "A",
#         "ttl": 3600,
#         "changetype": "DELETE",
#     })

# chunk_size = 250

# for i in range(0, len(records), chunk_size):
#     payload = {"rrsets": records[i:i+chunk_size]}
#     r = requests.patch(API, headers=headers, json=payload)
#     r.raise_for_status()
#     print(f"Deleted {i + len(payload['rrsets'])}/{len(records)}")






# query the zone to ensure that the system can handle all the records

# import requests
# import os
# import pathlib
# import simple_python_dotenv
# simple_python_dotenv.load_dotenv(pathlib.Path(__file__).parents[1] / ".env")
# KEY = os.getenv("PDNS_API_KEY","")
# print(requests.get(
#     f"http://127.0.0.1:8081/api/v1/servers/localhost/zones/eepy.page.",
#     headers={"X-API-Key": KEY},
#     timeout=10,
# ).json())
