name: Test checks

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:8.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MONGODB_TEST_URL: mongodb://localhost:27017/
      REDIS_TEST_URL: redis://localhost:6379/15

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Python3
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Ruff - Install
        run: pip install ruff

      - name: Ruff - Check linting
        run: ruff check .

      - name: Ruff - Check formatting
        run: ruff format --check .

  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyright

      - name: Run Pyright
        run: pyright --outputjson .
